version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    networks:
      - log_net

  logstash:
    build: logstash
    ports:
      - "5000:5000"
    networks:
      - log_net

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - log_net

  frontend:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - kibana
    networks:
      - log_net

networks:
  log_net:
    driver: bridge
